Added `dtt_excel_to_time()` to convert excel times to R times
poissonconsulting/dttr2 pull request #44
Opened 2024-10-11 18:05 UTC by dunkenwg

Also created tests for this function

2024-10-30 23:34 UTC, aylapear requested changes
We should add a tests for empty numeric values. What happens if we pass `numeric(0L)` to the function, does it do what we expect? 

The rest looks good otherwise

2024-11-12 17:02 UTC, dunkenwg commented
@aylapear, does everything look good now?

2024-11-15 22:54 UTC, aylapear requested changes
This looks good. Do not merge the pull request but please do a dev version bump and update the news file.

2024-12-02 18:42 UTC, aylapear approved these changes

2024-12-02 18:56 UTC, merged